# Generated by Django 5.1.7 on 2025-03-23 13:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination', models.CharField(choices=[('Colombo', 'Colombo'), ('Kandy', 'Kandy'), ('Galle', 'Galle'), ('Nuwara Eliya', 'Nuwara Eliya'), ('Ella', 'Ella'), ('Jaffna', 'Jaffna')], max_length=50)),
                ('theme', models.CharField(choices=[('Adventure & Outdoors', 'Adventure & Outdoors'), ('Leisure & Relaxation', 'Leisure & Relaxation'), ('Culture & Heritage', 'Culture & Heritage')], max_length=50)),
                ('check_in', models.DateField()),
                ('check_out', models.DateField()),
                ('transport', models.CharField(choices=[('Private', 'Private'), ('Public', 'Public'), ('Rental', 'Rental')], max_length=50)),
                ('accommodation_type', models.CharField(choices=[('Hotel', 'Hotel'), ('Villa', 'Villa'), ('Guesthouse', 'Guesthouse'), ('Resort', 'Resort')], max_length=50)),
                ('accommodation_tier', models.CharField(choices=[('Luxury', 'Luxury'), ('Mid-range', 'Mid-range'), ('Budget', 'Budget')], max_length=50)),
                ('travelers', models.PositiveIntegerField()),
                ('budget', models.DecimalField(decimal_places=2, max_digits=8)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trips', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TripPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('itinerary', models.JSONField()),
                ('cost_breakdown', models.JSONField()),
                ('trip', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='plan', to='api.trip')),
            ],
        ),
    ]
