# Generated by Django 5.1.7 on 2025-03-16 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_transpost_trip_transport'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='accommodation',
        ),
        migrations.AddField(
            model_name='trip',
            name='accommodation_tier',
            field=models.CharField(choices=[('Luxury', 'Luxury'), ('Mid-range', 'Mid-range'), ('Budget', 'Budget')], default='Luxury', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trip',
            name='accommodation_type',
            field=models.CharField(choices=[('Hotel', 'Hotel'), ('Villa', 'Villa'), ('Guesthouse', 'Guesthouse'), ('Hostel', 'Hostel'), ('B&B', 'B&B'), ('Resort', 'Resort')], default='Hotel', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='trip',
            name='destination',
            field=models.CharField(choices=[('Colombo', 'Colombo'), ('Kandy', 'Kandy'), ('Galle', 'Galle'), ('Nuwara Eliya', 'Nuwara Eliya'), ('Ella', 'Ella'), ('Jaffna', 'Jaffna')], max_length=50),
        ),
        migrations.AlterField(
            model_name='trip',
            name='theme',
            field=models.CharField(choices=[('Adventure & Outdoors', 'Adventure & Outdoors'), ('Leisure & Relaxation', 'Leisure & Relaxation'), ('Culture & Heritage', 'Culture & Heritage')], max_length=50),
        ),
        migrations.AlterField(
            model_name='trip',
            name='transport',
            field=models.CharField(choices=[('Private', 'Private'), ('Public', 'Public'), ('Rental', 'Rental')], max_length=50),
        ),
    ]
