# Generated by Django 5.1.7 on 2025-03-25 23:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_tripplan_trip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tripplan',
            name='trip',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='plan', to='api.trip'),
        ),
    ]
