# Generated by Django 5.1.7 on 2025-03-16 23:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_trip_accommodation_trip_accommodation_tier_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TripPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('itinerary', models.JSONField()),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=8)),
                ('trip', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='plan', to='api.trip')),
            ],
        ),
    ]
