# Generated by Django 5.1.7 on 2025-03-16 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_tripplan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tripplan',
            name='total_cost',
        ),
        migrations.AddField(
            model_name='tripplan',
            name='cost_breakdown',
            field=models.JSONField(default={}),
            preserve_default=False,
        ),
    ]
