# Generated by Django 5.1.7 on 2025-03-27 23:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='destination',
        ),
    ]
