# Generated by Django 5.1.7 on 2025-03-17 00:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_tripplan_total_cost_tripplan_cost_breakdown'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tripplan',
            name='cost_breakdown',
        ),
    ]
