# Generated by Django 5.1.7 on 2025-04-06 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_review_destination'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmergencyContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(choices=[('Colombo', 'Colombo'), ('Kandy', 'Kandy'), ('Galle', 'Galle'), ('Nuwara Eliya', 'Nuwara Eliya'), ('Ella', 'Ella'), ('Jaffna', 'Jaffna')], max_length=100)),
                ('service_type', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=150)),
                ('phone_number', models.CharField(max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
