# Generated by Django 5.1.7 on 2025-04-06 22:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_emergencycontact'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emergencycontact',
            old_name='location',
            new_name='destination',
        ),
    ]
