# Generated by Django 5.1.7 on 2025-03-17 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_tripplan_cost_breakdown'),
    ]

    operations = [
        migrations.AddField(
            model_name='tripplan',
            name='cost_breakdown',
            field=models.JSONField(default={}),
            preserve_default=False,
        ),
    ]
