# Generated by Django 5.1.7 on 2025-03-20 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_tripplan_cost_breakdown'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='accommodation_type',
            field=models.CharField(choices=[('Hotel', 'Hotel'), ('Villa', 'Villa'), ('Guesthouse', 'Guesthouse'), ('Resort', 'Resort')], max_length=50),
        ),
    ]
