# Generated by Django 5.1.7 on 2025-04-23 12:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_trip_destination_alter_trip_theme'),
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('google_place_id', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('beautified_name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('lat', models.FloatField()),
                ('lng', models.FloatField()),
                ('rating', models.FloatField(blank=True, null=True)),
                ('num_reviews', models.IntegerField(default=0)),
                ('types', models.JSONField()),
                ('photo_reference', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.destination')),
                ('theme', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.theme')),
            ],
        ),
    ]
