# Generated by Django 5.1.7 on 2025-04-23 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_place'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='photo_reference',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
