# Generated by Django 5.1.7 on 2025-04-24 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_place_photo_reference'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='visit_duration',
            field=models.PositiveIntegerField(default=60, help_text='Estimated visit duration in minutes'),
        ),
    ]
