# Generated by Django 5.1.7 on 2025-04-24 20:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_place_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accommodation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('google_place_id', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('lat', models.FloatField()),
                ('lng', models.FloatField()),
                ('rating', models.FloatField(blank=True, null=True)),
                ('types', models.JSONField(default=list)),
                ('photo_reference', models.CharField(blank=True, max_length=1024, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='accommodations/')),
                ('category', models.CharField(choices=[('Hotel', 'Hotel'), ('Villa', 'Villa'), ('Guesthouse', 'Guesthouse'), ('Resort', 'Resort')], max_length=20)),
                ('tier', models.CharField(choices=[('Budget', 'Budget'), ('Mid-range', 'Mid-range'), ('Luxury', 'Luxury')], max_length=20)),
                ('price_per_night_per_person', models.PositiveIntegerField(help_text='LKR')),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.destination')),
            ],
        ),
    ]
