# Generated by Django 5.1.7 on 2025-04-24 23:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_tripplan_accommodation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emergencycontact',
            name='description',
            field=models.TextField(blank=True, default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='emergencycontact',
            name='destination',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.destination'),
        ),
        migrations.AlterField(
            model_name='emergencycontact',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='emergencycontact',
            name='service_type',
            field=models.CharField(max_length=50),
        ),
    ]
