# Generated by Django 5.1.7 on 2025-04-24 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_alter_emergencycontact_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='emergencycontact',
            name='lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='emergencycontact',
            name='lng',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
