# Generated by Django 5.1.7 on 2025-04-24 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_emergencycontact_lat_emergencycontact_lng'),
    ]

    operations = [
        migrations.AddField(
            model_name='emergencycontact',
            name='google_place_id',
            field=models.CharField(default='', max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
