# Generated by Django 5.2 on 2025-05-11 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_emergencycontact_google_place_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='price_per_person',
            field=models.PositiveIntegerField(default=0, help_text='Estimated cost in LKR per person to visit this place'),
        ),
    ]
