# Generated by Django 5.2 on 2025-05-12 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_place_price_per_person'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='price_per_person',
        ),
    ]
